### ISSUE TITLE
Expo 51 support

### ISSUE THREAD

**Issue by patrickkeenan** [daily-co/rn-daily-js-expo-config-plugin#11]
# Feature request

Support 51

# Why you need this

NPM complains and does not let me install this version on the latest expo

# Alternatives you've considered

Downgrading: Lose all the updates in 51, other libraries fail.

# Additional context

Would love to know if this will continue to be supported. If not, maybe there's a way to outline the implementation so it can be adapted. Thanks for the library!

**Comment by filipi87** [comment]
Hi @patrickkeenan, we plan to keep supporting this plugin.

I will let you know as soon as we add support for Expo 51.

Thank you for reporting this.

**Comment by filipi87** [comment]
Hi @patrickkeenan , the plugin is already available: https://www.npmjs.com/package/@daily-co/config-plugin-rn-daily-js
