### ISSUE TITLE
[FEATURE-REQUEST] Expo 52 support

### ISSUE THREAD

**Issue by OctopBP** [daily-co/rn-daily-js-expo-config-plugin#15]
Expo 52 is out. Could you please add support for this?

**Comment by augusdin** [comment]
Really need support for Expo 5.2, hope to see an update soon. Thanks!

**Comment by augusdin** [comment]
Really need support for Expo 52, hope to see an update soon. Thanks!

**Comment by filipi87** [comment]
Hi, we have an open [PR](https://github.com/daily-co/rn-daily-js-expo-config-plugin/pull/16) to add support for it. As soon as we merge it, we can publish the latest version. Thank you for reporting this.

**Comment by filipi87** [comment]
The version 0.0.7 with Expo 52 support has been released:
- https://www.npmjs.com/package/@daily-co/config-plugin-rn-daily-js

We have also updated our demo, to use Expo 52:
- https://github.com/daily-demos/daily-expo-demo/pull/10
- This one should be merged soon.

Thank you again for reporting this, and let me know in case you need any help.
