### ISSUE TITLE
Update to Expo SDK 49

### ISSUE THREAD

**Issue by lele0108** [daily-co/rn-daily-js-expo-config-plugin#6]
See #5

**Comment by lele0108** [comment]
@filipi87 Can we help review and land? Blocking usage of Daily with EAS / Expo

**Comment by filipi87** [comment]
Hi @lele0108 , The version [0.0.3](https://www.npmjs.com/package/@daily-co/config-plugin-rn-daily-js) is available.

Thanks for helping landing this. 🙂
